services:
  mysql:
    image: mysql:8.0
    container_name: mysql_global
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - global_network

volumes:
  mysql_data:

networks:
  global_network:
    external: true
